### ISSUE TITLE
Usage with psc-packages

### ISSUE THREAD

**Issue by bbarker** [ajnsit/purescript-concur-starter#1]
Maybe this isn't supported; I tried the following:

```
$ pulp --psc-package browserify
* Browserifying project in /wd
* Building project in /wd
* Build successful.
* Browserifying...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'react' from '/wd/output/React'
    at /usr/local/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

Note that `pulp --psc-package build` completes.

I have the following React code being pulled in:

```
$ ls output/React*
output/React:
externs.json  foreign.js  index.js

output/React.DOM:
externs.json  index.js

output/React.DOM.Dynamic:
externs.json  index.js

output/React.DOM.Props:
externs.json  foreign.js  index.js

output/React.DOM.SVG:
externs.json  index.js

output/React.DOM.SVG.Dynamic:
externs.json  index.js

output/React.SyntheticEvent:
externs.json  foreign.js  index.js

output/ReactDOM:
externs.json  foreign.js  index.js
```

**Comment by ajnsit** [comment]
You may just need an `npm install` to pull in the react library.

**Comment by bbarker** [comment]
I think that covers it, though the resulting index.js did not work for me. Rather than struggling to get that working, it seems that using multiple package managers is not ideal, so I think I'll just stick with using `npm`.

Though a bit confused about bower's role in all this still.

**Comment by ajnsit** [comment]
So typically in Purescript projects, npm/yarn is only used to pull in external javascript dependencies (like react in this case). For pulling in purescript dependencies you can use either bower (which I personally use for my projects) or psc-package. There are technical reasons why we don't use npm to manage purescript dependencies, the biggest being that npm doesn't have a way to disallow multiple versions of the same library in the dependency tree.

As for psc-package vs bower for purescript dependencies - psc-package never gained enough traction in the purescript community and there are some newer solutions like spago already on the rise. Until then I would recommend using bower for the smoothest experience.

So to confirm, for building purescript projects which have external js dependencies, you would typically follow this sequence -

    # Install external js deps
    npm install
    # Install purescript library deps
    bower install
    # Build project
    pulp build

**Comment by ajnsit** [comment]
Also, can you elaborate why the resulting index.js didn't work for you? Are you getting an error when trying to run it?

**Comment by bbarker** [comment]
Thanks for the explanations, very helpful. 

Unfortunately I don't remember the exact error message and it was happening in between commits. To be clear this was when I was using the `pulp --psc-package build` rather than the `bower`-based instructions. There was an [illegal character](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Illegal_character) on line one of the index.js file - but it was rather long and didn't see anything odd at first glance (at least near the start of the line).

**Comment by ajnsit** [comment]
Glad it started working now!
