### ISSUE TITLE
Parcel 2 is broken

### ISSUE THREAD

**Issue by drshade** [ajnsit/purescript-concur-starter#24]
Hello

I get the following error when trying to run this starter project:
```
🚨 Build failed.

@parcel/transformer-js: Browser scripts cannot have imports or exports.

  /Users/tom/repo/purescript-concur-starter/index.js:1:1
  > 1 | import Main from "./output/Main";
  >   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2 | Main.main();
    3 |

  /Users/tom/repo/purescript-concur-starter/index.html:9:3
     8 |   <div id="root"></div>
  >  9 |   <script type="application/javascript" src="index.js"></script>
  >    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ The environment was originally created here
    10 | </body>
    11 | </html>

  💡 Add the type="module" attribute to the <script> tag.
```

I am fairly sure it's because parcel 2 is broken and not yet ready (it is marked "beta"). I have been maintaining a separate purescript-concur-starter repo [here](https://github.com/drshade/purescript-concur-starter-1), which initially upgraded to purescript 0.14 package sets etc (I did submit you a PR at the time), and now i've updated it to remain using parcel v1 which works better for me and my team. 

Would you consider downgrading to parcel v1 until parcel v2 is officially out of beta? I see there is an RC available, but i haven't had the time to test it yet. Happy to submit you a PR for this?

Thanks a mil,
Tom

**Comment by ajnsit** [comment]
Thanks @drshade! This should be fixed in https://github.com/purescript-concur/purescript-concur-starter/commit/f57e3938babb5f6f7090d594adce8ab476d19be2.
