### ISSUE TITLE
Live reloading not working while modifying src/Main.purs

### ISSUE THREAD

**Issue by shubhamkumar13** [ajnsit/purescript-concur-starter#4]
I tried to change the Main.purs file, specifically the "Hello Sailor!" to "Hello Sailor" but I couldn't see the change reflected on the page

**Comment by ajnsit** [comment]
You need an editor which runs the purescript build automatically. I use spacemacs which does that. If you don't have that, maybe you can run a separate watcher program.

**Comment by ajnsit** [comment]
@shubhamkumar13 I'm going to close this issue. Please feel free to reopen if needed.
