### ISSUE TITLE
How to use with react-devtools

### ISSUE THREAD

**Issue by bbarker** [ajnsit/purescript-concur-starter#8]
In relation to https://github.com/purescript-concur/purescript-concur-react/issues/41, I've been wondering if react-devtools might provide some insight. It might be good to build this functionality into this starter project, so that one could do things like build a development or profiling build.

However, I've been unable to do this so far, and I'm guessing it is in relation to `parcel`, though I'm not sure - most react projects seem to use webpack, and all the devtools instructions I've seen have been for webpack. Whenever I go to the profiling tab of react dev tools on my parcel/concur project, I'm unable to profile. An alternative, if a development build is enabled, is to [use the performance tab](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab) which is a standard feature of the browser.

I've tried setting `NODE_ENV="development" parcel build ...`, but this didn't appear to help in my case.

**Comment by bbarker** [comment]
Confirmed that profiling works when using webpack ([example repo](https://github.com/bbarker/concur-webpack-template), [snapshot](https://github.com/bbarker/concur-webpack-template/tree/943d3c9b0f15b3140322dc7897977dbd0a692e73)).

In particular, the react Profiler (tried in Chromium) works, though there is only one component showing up: `Concur`. Still, it is a start.

**Comment by ajnsit** [comment]
Thanks @bbarker!
